const data={
    "Pending": [
        {
            id:1,
            name:"Sam Altman",
            email:"samaltman123@gmail.com",
            link:"#",
            riskLevel:"Medium",
            triggerReason:"IP Change",
            inQueue:4,
            dateAdded:"12 Oct,2023",
            prevReview:"Yes",
            prevReviewDate:"23 Aug,2023"
        },
        {
            id:2,
            name:"Sameer Choubey",
            email:"sameerchoubey@gmail.com",
            link:"#",
            riskLevel:"High",
            triggerReason:"FIFO",
            inQueue:4,
            dateAdded:"12 Oct,2023",
            prevReview:"No",
        },
        {
            id:3,
            name:"Adarsh Panikkar",
            email:"adarsh@onjuno.com",
            link:"#",
            riskLevel:"Low",
            triggerReason:"IP Change",
            inQueue:5,
            dateAdded:"12 Oct,2023",
            prevReview:"No",
            prevReviewDate:""
        },
        {
            id:4,
            name:"Pratik Shetty",
            email:"pratik@gmail.com",
            link:"#",
            riskLevel:"High",
            triggerReason:"FIFO",
            inQueue:5,
            dateAdded:"12 Oct,2023",
            prevReview:"Yes",
            prevReviewDate:"12 Sep, 2023"
        },
        {
            id:5,
            name:"Elon Musk",
            email:"elon@twitterceo.com",
            link:"#",
            riskLevel:"Low",
            triggerReason:"FIFO",
            inQueue:5,
            dateAdded:"12 Oct,2023",
            prevReview:"Yes",
            prevReviewDate:"12 Sep, 2023"
        },
        {
            id:6,
            name:"Trina Kundu",
            email:"trina@onjuno.com",
            link:"#",
            riskLevel:"Low",
            triggerReason:"FIFO",
            inQueue:5,
            dateAdded:"12 Oct,2023",
            prevReview:"Yes",
            prevReviewDate:"12 Sep, 2023"
        },
    ],
    "Completed":[
        {
            id:7,
            name:"Sam Altman",
            email:"samaltman123@gmail.com",
            link:"#",
            riskLevel:"Medium",
            actionReason:"Flagged",
            timeClose:14,
            dateAdded:"12 Oct,2023",
            actionTaken:"Neil",
            actionTakenEmail:"neil@onjuno.com",
        },
        {
            id:8,
            name:"Sameer Chubey",
            email:"sameerchoubey123@gmail.com",
            link:"#",
            riskLevel:"High",
            actionReason:"Closed",
            timeClose:14,
            dateAdded:"12 Oct,2023",
            actionTaken:"Pratik",
            actionTakenEmail:"pratik@onjuno.com",
        },
        {
            id:9,
            name:"Adarsh Panikkar",
            email:"adarsh@onjuno.com",
            link:"#",
            riskLevel:"Low",
            actionReason:"Cleared",
            timeClose:14,
            dateAdded:"12 Oct,2023",
            actionTaken:"Prashanth",
            actionTakenEmail:"prashanth@onjuno.com",
        },
        {
            id:10,
            name:"Pratik Shetty",
            email:"pratik@gmail.com",
            link:"#",
            riskLevel:"High",
            actionReason:"SOI requested",
            timeClose:14,
            dateAdded:"12 Oct,2023",
            actionTaken:"Rasleen Kaur",
            actionTakenEmail:"rasleen@onjuno.com",
        },
        {
            id:11,
            name:"Elon Musk",
            email:"elon@twitterceo.com",
            link:"#",
            riskLevel:"Low",
            actionReason:"Flagged",
            timeClose:15,
            dateAdded:"12 Oct,2023",
            actionTaken:"Pratik Shetty",
            actionTakenEmail:"pratik@onjuno.com",
        },
        {
            id:12,
            name:"Trina Kundu",
            email:"trina@onjuno.com",
            link:"#",
            riskLevel:"Low",
            actionReason:"closed",
            timeClose:15,
            dateAdded:"12 Oct,2023",
            actionTaken:"Varun Deshpande",
            actionTakenEmail:"varun@onjuno.com",
        },
        
    ]
}

export default data;